#!/bin/bash
# Startup script for Databricks Apps

# Ensure HOME is set — Databricks Apps may leave it empty
if [ -z "$HOME" ] || [ "$HOME" = "/" ]; then
    export HOME="/home/$(whoami)"
    mkdir -p "$HOME" 2>/dev/null || export HOME="/tmp/app-home"
    mkdir -p "$HOME"
fi

export PATH="$HOME/.local/bin:$PATH"

# Per-environment overrides (TRANSLATE_VOLUME_PATH, SOFFICE_*) generated by
# the deploy script and uploaded alongside the source files. Absent in local
# dev and in the Git Folder — app.yaml defaults apply in that case.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/target_config.env" ]; then
    # shellcheck source=/dev/null
    source "$SCRIPT_DIR/target_config.env"
fi

export TZ='Europe/Paris'

exec uvicorn server.app:app "$@"
